pardisohost = {'sisyphus1';...
    'sisyphus2';...
    'sisyphus3';...
    'sisyphus4';...
    'sisyphus5';...
    'sisyphus6';...
    'sisyphus7';...
    'sisyphus8';...
    'sisyphus9';...
    'sisyphus10'};